### ISSUE TITLE
 V3 Model with the Demo App Stream Function Causes Sluggish Performance with Zoom Video

### ISSUE THREAD

**Issue by gavintreetree** [argmaxinc/WhisperKit#274] opened 2024-12-10 19:05 UTC
Firstly, thank you for the incredible work in creating and open-sourcing this project—it’s been running well for my personal projects. I’d like to report an issue I’ve encountered and seek insights into potential causes:

While using the openai_whisper-large-v3-v20240930_626MB model’s and running on the stream in the demo app in MacOS, I noticed a significant performance issue when running Zoom video simultaneously. The Zoom video becomes very sluggish and unresponsive. This issue does not occur with others older models like openai_whisper-small, or openai_whisper-base. 

It appears to be specific to the newly added V3 model so far.
I have been trying to debug into it but no sure where I should start, I'm wondering what are the potential cause and any guidance is appreciated 

Steps to Reproduce:
	1.	In the Demo app, Run the openai_whisper-large-v3-v20240930_626MB model with the stream transcribe.
	2.	Open Zoom and start a video call.
	3.	Observe the video performance in Zoom.

Expected Behavior:
Zoom video should run smoothly while the WhisperKit stream function is active.

Actual Behavior:
Zoom video becomes sluggish and unresponsive when the V3 stream function is running.

Environment:
	•	WhisperAX Version: 0.4.0
	•	Model Used: openai_whisper-large-v3-v20240930_626MB
	•	Zoom Version: 6.2.11 (43613)
	•	Operating System: MacOS 15.1
	•	Hardware:  MacBook Pro M1, 2021

**Comment by ZachNagengast** [comment] 2024-12-11 01:06
Thanks for the report, are you using GPU or ANE for inference? One thing that would be helpful is if you could you run [asitop](https://github.com/tlkh/asitop) during a transcription and send a screenshot here of how it looks when it becomes sluggish.

**Comment by atiorh** [comment] 2024-12-11 17:11
Indeed, if you configured WhisperKit to use the GPU, Zoom and Whisperkit would be contending for compute resources (especially on an entry-level M1).

**Comment by gavintreetree** [comment] 2024-12-11 20:34
@atiorh 
![Screenshot 2024-12-11 at 12 33 15 PM](https://github.com/user-attachments/assets/2c212d8d-cbbf-47a8-8d89-33efcdcf41f6)
Using Neural Engine still have the issues though

**Comment by gavintreetree** [comment] 2024-12-11 20:35
@ZachNagengast Hi Zach, I configured using both Audio Encode and text decoder on Neural Engine. I will run [asitop](https://github.com/tlkh/asitop) later

**Comment by gavintreetree** [comment] 2024-12-11 20:45
@ZachNagengast Hi Zach this is the screenshot of the asitop, thank you for the instrcutions!
![Screenshot 2024-12-11 at 12 44 00 PM](https://github.com/user-attachments/assets/59159ac3-f917-44d6-8312-64e7897ddd3b)
![Screenshot 2024-12-11 at 12 43 15 PM](https://github.com/user-attachments/assets/83e865e0-05e0-4a2d-a791-57b9f7253059)

**Comment by ZachNagengast** [comment] 2024-12-11 21:03
Thanks for the screenshots, can you confirm that the zoom video was sluggish during this screenshot? The compute resources look to be within normal bounds, but what stands out to me is the high memory usage, specifically the swap `5.7/7.0 GB`. You may want to experiment with closing any background processes that are using a lot of memory (which should lower the swap number) and check if the sluggishness goes away. In the meantime, I will try to reproduce this and see if there is a root cause somewhere.

**Comment by gavintreetree** [comment] 2024-12-11 23:28
@ZachNagengast you are right, once I turned off the background blur in zoom, it was no longer sluggish !

**Closed** 2024-12-14 19:08 UTC
