### ISSUE TITLE
Incorrect word timestamp when using VAD

### ISSUE THREAD

**Issue by finnvoor** [argmaxinc/WhisperKit#160] opened 2024-06-06 08:59 UTC
The following audio when transcribed using base.en, wordTimestamps: true, and chunkingStrategy: .vad outputs a word " [ Silence ]" with an incorrect timestamp (~30s offset from the surrounding words). I'm not sure if this is VAD related or just only occurs in this audio with VAD chunking enabled.

```swift
let pipe = try await WhisperKit(model: "base.en")
let result = try await pipe.transcribe(
    audioPath: "~/Downloads/Detail_20240606094159.m4a",
    decodeOptions: DecodingOptions(
        skipSpecialTokens: true,
        wordTimestamps: true,
        chunkingStrategy: .vad
    )
)
print(result.segments
    .compactMap(\.words)
    .flatMap { $0 }
    .map { "\($0.word), \($0.start), \($0.end)" }
    .joined(separator: "\n"))
```

outputs:

```
...
 scoop, 39.96, 40.36
 them, 40.559998, 40.62
 out., 40.62, 40.84
 [ Silence ], 70.36, 70.36
 Now,, 46.44, 46.5
 with, 46.859997, 46.899998
 some, 46.899998, 47.019997
...
```

[Detail_20240606094159.m4a.zip](https://github.com/user-attachments/files/15612553/Detail_20240606094159.m4a.zip)

**Comment by atiorh** [comment] 2024-07-01 14:20
@finnvoor Is this problem fully resolved? If not, please reopen :)

**Comment by finnvoor** [comment] 2024-07-01 14:23
Definitely not resolved, it's actually fairly common. I implemented a workaround in Detail today since it was causing a lot of issues (filter out words where startTime > next word.startTime). We're on 0.7.2, should I test main?

**Comment by atiorh** [comment] 2024-07-01 14:57
We are actively working on identifying a fix. Did this workaround prove useful in your failure cases? We will keep looking for the root cause but this filter is definitely a worthwhile guardrail to have regardless. Let me know if you are open to PRing it

**Comment by finnvoor** [comment] 2024-07-01 15:08
Yeah, the filter seems to fix everything since it's usual 1-2 tokens that are ~30s ahead of the tokens around them.

I can open a PR, it's definitely a workaround not a fix though.

**Comment by ZachNagengast** [comment] 2024-07-01 16:00
> Yeah, the filter seems to fix everything since it's usually 1-2 tokens that are ~30s ahead of the tokens around them.
> 
> I can open a PR, it's definitely a workaround not a fix though.

This is a good work around to have in any case, internally it only has this logic per segment. Do you know if the [Silence] is it's own segment from the flatmap, or is it actually a word placed in a good segment out of order?

**Comment by finnvoor** [comment] 2024-07-01 16:09
It's in a segment on it's own, the full segment is "<|startoftranscript|><|0.00|> [ Silence ]<|10.00|><|endoftext|>". This only happens with VAD + wordTimestamps, and the bad timestamp is applied somewhere in `addWordTimestamps`

**Comment by ZachNagengast** [comment] 2024-07-01 16:10
Got it, thank you @finnvoor super helpful

**Comment by atiorh** [comment] 2024-07-16 07:16
I believe this issue was resolved with https://github.com/argmaxinc/WhisperKit/releases/tag/v0.8.0 (I can not reproduce it anymore). Please reopen if this persists for you or a similar issue pops up in a different input audio file.

**Closed by atiorh** 2024-07-16 07:16 UTC
Labels: bug, good first issue, help wanted

**Comment by finnvoor** [comment] 2024-07-16 09:30
Just confirmed it does seem to be fixed, thanks!
